### ISSUE TITLE
[Bug]: InstallerUrl doesn't not get the correct arch package

### ISSUE THREAD

**Issue by ttrunck** [vedantmgoyal2009/vedantmgoyal2009#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Lock at this PR: https://github.com/microsoft/winget-pkgs/pull/34553
The InstallerUrl are switched between the x64 and the arm64 arch.

I created a PR on the winget-pkgs repo to fix 2.0.3/2.0.2 and 2.0.0 which are the only impacted version (https://github.com/microsoft/winget-pkgs/pull/34772) but obviously this tool should be fixed (or Zettlr should be removed from here).

I have no idea if other packages are impacted.

**Comment by vedantmgoyal2009** [comment]
Yes, I'm aware of that and Easton (one of the moderators) had suggested to look into the last existing manifest and sort the URLs accordingly. I am still thinking of a better solution to avoid these kind of errors. BTW, thanks for reporting the issue, I will try to fix this as fast as possible.

@Allcontributors please add @ttrunck for bugs

**Comment by vedantmgoyal9** [comment]
I haven't witnessed the shuffling of installer URLs among architectures in the past few months, so I believe this has been rectified with the updates made to automation after this issue was opened.

Also, YamlCreate.ps1 v3.0 will be released in the next few months, so there's hardly any possibility it will happen again once the automation is updated to use the new version.
